/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SoundRouteImport } from './routes/sound'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as GenresIdRouteImport } from './routes/genres.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundRoute = SoundRouteImport.update({
  id: '/sound',
  path: '/sound',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenresRoute,
} as any)
const GenresIdRoute = GenresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GenresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genres': typeof GenresRouteWithChildren
  '/license': typeof LicenseRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/sound': typeof SoundRoute
  '/studio': typeof StudioRoute
  '/genres/$id': typeof GenresIdRoute
  '/genres/': typeof GenresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/license': typeof LicenseRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/sound': typeof SoundRoute
  '/studio': typeof StudioRoute
  '/genres/$id': typeof GenresIdRoute
  '/genres': typeof GenresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genres': typeof GenresRouteWithChildren
  '/license': typeof LicenseRoute
  '/method': typeof MethodRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell': typeof SellRoute
  '/sound': typeof SoundRoute
  '/studio': typeof StudioRoute
  '/genres/$id': typeof GenresIdRoute
  '/genres/': typeof GenresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genres'
    | '/license'
    | '/method'
    | '/pricing'
    | '/privacy'
    | '/sell'
    | '/sound'
    | '/studio'
    | '/genres/$id'
    | '/genres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/license'
    | '/method'
    | '/pricing'
    | '/privacy'
    | '/sell'
    | '/sound'
    | '/studio'
    | '/genres/$id'
    | '/genres'
  id:
    | '__root__'
    | '/'
    | '/genres'
    | '/license'
    | '/method'
    | '/pricing'
    | '/privacy'
    | '/sell'
    | '/sound'
    | '/studio'
    | '/genres/$id'
    | '/genres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenresRoute: typeof GenresRouteWithChildren
  LicenseRoute: typeof LicenseRoute
  MethodRoute: typeof MethodRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SellRoute: typeof SellRoute
  SoundRoute: typeof SoundRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound': {
      id: '/sound'
      path: '/sound'
      fullPath: '/sound'
      preLoaderRoute: typeof SoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/$id': {
      id: '/genres/$id'
      path: '/$id'
      fullPath: '/genres/$id'
      preLoaderRoute: typeof GenresIdRouteImport
      parentRoute: typeof GenresRoute
    }
  }
}

interface GenresRouteChildren {
  GenresIdRoute: typeof GenresIdRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresIdRoute: GenresIdRoute,
  GenresIndexRoute: GenresIndexRoute,
}

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenresRoute: GenresRouteWithChildren,
  LicenseRoute: LicenseRoute,
  MethodRoute: MethodRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SellRoute: SellRoute,
  SoundRoute: SoundRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
